services:
  app_stg:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: debate_match_app_stg
    restart: unless-stopped
    environment:
      - "APP_ENV=staging"
      - "APP_URL=https://stg.debate-match.com"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "REDIS_HOST=redis_stg"
      - "REDIS_PORT=6379"
      - "PUSHER_APP_ID=${PUSHER_APP_ID}"
      - "PUSHER_APP_KEY=${PUSHER_APP_KEY}"
      - "PUSHER_APP_SECRET=${PUSHER_APP_SECRET}"
      - "PUSHER_HOST=${PUSHER_HOST}"
      - "PUSHER_PORT=${PUSHER_PORT}"
      - "PUSHER_SCHEME=${PUSHER_SCHEME}"
      - "PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}"
      - "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
      - "SESSION_DRIVER=${SESSION_DRIVER:-file}"
      - "CACHE_DRIVER=${CACHE_DRIVER:-file}"
      - "QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}"
      - "SENTRY_LARAVEL_DSN=${SENTRY_LARAVEL_DSN}"
      - "SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-1.0}"
    volumes:
      - ./.env:/var/www/html/.env:ro
    networks:
      - sail_stg
    depends_on:
      - redis_stg

  worker_stg:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: debate_match_worker_stg
    restart: unless-stopped
    command: php artisan queue:work sqs --sleep=3 --tries=3 --timeout=300 --max-jobs=500 --max-time=1800
    environment:
      - "APP_ENV=staging"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "PUSHER_APP_ID=${PUSHER_APP_ID}"
      - "QUEUE_CONNECTION=sqs"
      - "SQS_QUEUE=${SQS_QUEUE}"
    volumes:
      - ./.env:/var/www/html/.env:ro
    networks:
      - sail_stg
    depends_on:
      - app_stg
      - redis_stg

  redis_stg:
    image: redis:7-alpine
    container_name: debate_match_redis_stg
    restart: unless-stopped
    volumes:
      - redis-data-stg:/data
    networks:
      - sail_stg
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  sail_stg:
    driver: bridge

volumes:
  redis-data-stg:
    driver: local
